# frozen_string_literal: true

require 'open-uri'
require 'json'

Character.destroy_all
Inhabit.destroy_all
Specie.destroy_all
Planet.destroy_all
Starship.destroy_all
Page.destroy_all

csv_file_characters = Rails.root + 'db/characters.csv'
options = { file_encoding: 'iso-8859-1' } # Only needed if the CSV file was generated by Excel.
characters_csv = SmarterCSV.process(csv_file_characters, options) # Pass the "options" hash as a second argument if CSV was created by Excel.

csv_file_planets = Rails.root + 'db/planets.csv'
options = { file_encoding: 'iso-8859-1' } # Only needed if the CSV file was generated by Excel.
planets_csv = SmarterCSV.process(csv_file_planets, options) # Pass the "options" hash as a second argument if CSV was created by Excel.

csv_file_species = Rails.root + 'db/species.csv'
options = { file_encoding: 'iso-8859-1' } # Only needed if the CSV file was generated by Excel.
species_csv = SmarterCSV.process(csv_file_species, options) # Pass the "options" hash as a second argument if CSV was created by Excel.

csv_file_starships = Rails.root + 'db/starships.csv'
options = { file_encoding: 'iso-8859-1' } # Only needed if the CSV file was generated by Excel.
starships_csv = SmarterCSV.process(csv_file_starships, options) # Pass the "options" hash as a second argument if CSV was created by Excel.

planets_count = planets_csv.count
characters_count = characters_csv.count
species_count = species_csv.count
starships_count = starships_csv.count
f = planets_csv.first
puts f[:name]
puts f[:population]
puts planets_count
puts characters_count
puts species_count
puts starships_count

# create Starships
# starship = Starship.new
starship = Starship.new
planet = Planet.new
specie = Specie.new

rand(10..starships_count).times do
  name = starships_csv[rand(starships_csv.length)]
  # name and model presence: true
  starship = Starship.create(
    name: name[:name],
    model: name[:model],
    crew: name[:crew]
  )

  # rand(21..planetsCount).times do
  name = planets_csv[rand(planets_csv.length)]
  # name and model presence: true
  planet = Planet.create(
    name: Faker::Movies::StarWars.planet,
    population: name[:population]
  )
  # end

  # rand(15..speciesCount).times do
  name = species_csv[rand(species_csv.length)]
  # name and model presence: true
  specie = Specie.create(
    name: name[:name],
    language: name[:language]
  )
  # end

  rand(50..100).times do
    name = characters_csv[rand(characters_csv.length)]
    Character.create(
      name: name[:name],
      starship_id: starship.id,
      planet_id: planet.id,
      specie_id: specie.id
    )
    # name: name[:name]
    # puts character.name
  end
end

rand(100..200).times do
  s = Specie.order('random()').first.id
  p = Planet.order('random()').first.id
  # puts s.specie_id
  # puts p.planet_id
  Inhabit.create(
    planet_id: p,
    specie_id: s
  )
end

Page.create(title: 'About Us', content: 'Please fill this in.', permalink: 'about_us')

puts "Generated #{Starship.count} starships."
puts "Generated #{Planet.count} planets."
puts "Generated #{Specie.count} species."
puts "Generated #{Character.count} characters."
puts "Generated #{Inhabit.count} inhabits."
