# frozen_string_literal: true

Character.destroy_all
Inhabit.destroy_all
Specie.destroy_all
Planet.destroy_all
Starship.destroy_all

csv_file_characters = Rails.root + 'db/characters.csv'
options = { file_encoding: 'iso-8859-1' } # Only needed if the CSV file was generated by Excel.
characters = SmarterCSV.process(csv_file_characters, options) # Pass the "options" hash as a second argument if CSV was created by Excel.

csv_file_planets = Rails.root + 'db/planets.csv'
options = { file_encoding: 'iso-8859-1' } # Only needed if the CSV file was generated by Excel.
planets = SmarterCSV.process(csv_file_planets, options) # Pass the "options" hash as a second argument if CSV was created by Excel.

csv_file_species = Rails.root + 'db/species.csv'
options = { file_encoding: 'iso-8859-1' } # Only needed if the CSV file was generated by Excel.
species = SmarterCSV.process(csv_file_species, options) # Pass the "options" hash as a second argument if CSV was created by Excel.

csv_file_starships = Rails.root + 'db/starships.csv'
options = { file_encoding: 'iso-8859-1' } # Only needed if the CSV file was generated by Excel.
starships = SmarterCSV.process(csv_file_starships, options) # Pass the "options" hash as a second argument if CSV was created by Excel.

planetsCount = planets.count
charactersCount = characters.count
speciesCount = species.count
starshipsCount = starships.count
f = planets.first
puts f[:name]
puts f[:population]

# create Starships
rand(1..starshipsCount).times do
  name = starships[rand(starships.length)]
  # name and model presence: true
  starship = Starship.create(
    name: name,
    model: name[:model],
    crew: name[:crew]
  )
end

# create Planets
rand(1..planetsCount).times do
  name = planets[rand(planets.length)]
  # name and model presence: true
  planet = Planet.create(
    name: name,
    population: name[:population]
  )
end

# create Species
rand(1..speciesCount).times do
  name = species[rand(species.length)]
  # name and model presence: true
  language = Specie.create(
    name: name,
    language: name[:language]
  )
end

puts "Generated #{Starship.count} starships."
puts "Generated #{Planet.count} planets."
puts "Generated #{Specie.count} species."
